# Machine Learning Zoomcamp



## 1.7 Introduction to NumPy


#### Plan:
    #### Creating arrays
    #### Multi-dementional arrays
    #### Randomly generated arrays
    #### Element-wise operations
    #### Comparison operations
    #### Logical operations
    #### Summarizing operations

In [1]:
import numpy as np


In [4]:
np.__version__

'1.21.5'

### Creating arrays

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [20]:
a = np.array([1, 2, 3, 5, 7, 12])


In [27]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [28]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional arrays

In [37]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [40]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
n[0, 1] = 20

In [42]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [43]:
n[:, 2]

array([3, 6, 9])

### Randomly generated arrays

In [67]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [69]:
np.random.seed(2)
100 * np.random.rand(5, 2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

### Element-wise operations

In [71]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [72]:
a*2

array([0, 2, 4, 6, 8])

In [76]:
a+2

array([2, 3, 4, 5, 6])

In [77]:
b = a+2.32

### Comparisons

In [75]:
a>=2

array([False, False,  True,  True,  True])

In [78]:
a>5

array([False, False, False, False, False])

In [80]:
a[a<b]

array([0, 1, 2, 3, 4])

### Summarizing operations

In [82]:
a.min()

0

In [83]:
a.sum()

10

In [84]:
a.mean()

2.0

In [85]:
a.std()

1.4142135623730951

In [2]:
__version__

NameError: name '__version__' is not defined

### Homework 1


In [7]:
np.__version__

'1.21.5'

In [9]:
wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

SyntaxError: invalid syntax (1636291068.py, line 1)

In [97]:
df = pd.read_csv('data.csv')

In [46]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [50]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [55]:
df.groupby('Make').Model.nunique() #number of unique audi car models

Make
Acura            18
Alfa Romeo        1
Aston Martin     12
Audi             34
BMW              39
Bentley          18
Bugatti           1
Buick            20
Cadillac         30
Chevrolet        63
Chrysler         19
Dodge            33
FIAT              5
Ferrari          14
Ford             51
GMC              30
Genesis           1
HUMMER            2
Honda            21
Hyundai          22
Infiniti         38
Kia              16
Lamborghini       6
Land Rover       11
Lexus            46
Lincoln          16
Lotus             5
Maserati          8
Maybach           3
Mazda            31
McLaren           4
Mercedes-Benz    40
Mitsubishi       22
Nissan           32
Oldsmobile       18
Plymouth         10
Pontiac          20
Porsche          12
Rolls-Royce      10
Saab              8
Scion             8
Spyker            1
Subaru           16
Suzuki           16
Tesla             1
Toyota           39
Volkswagen       31
Volvo            26
Name: Model, dtype: int64

In [56]:
df.isnull().sum() #cols with missing vales

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [62]:
df['Engine Cylinders'].mean() #Find the median value of "Engine Cylinders" column in the dataset. 

5.628828677213059

In [69]:

df['Engine Cylinders'].value_counts() #Next, calculate the most frequent value of the same "Engine Cylinders".


4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [72]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4) #fill column

In [73]:
df.isnull().sum() #cols with missing vales

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [74]:
df['Engine Cylinders'].mean() #Find the median value of "Engine Cylinders" column in the dataset after filling

5.624727211683734

In [96]:
df['Make']

KeyError: 'Make'

In [93]:
dfEE = df[['Engine HP', 'Engine Cylinders']]

In [99]:
dfLotus = df.loc[df['Make'] == 'Lotus'] #select all Lotuses

In [101]:
dfLotus = dfLotus[['Engine HP', 'Engine Cylinders']] #Select only columns "Engine HP", "Engine Cylinders".


In [105]:
dfLotusDD = dfLotus.drop_duplicates()

In [110]:
dfLotusDD

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [112]:
X = dfLotusDD.to_numpy()

In [125]:
XTX = np.dot(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [127]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [129]:
type(y)

numpy.ndarray

In [132]:
invX = np.linalg.inv(XTX)
invX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [133]:
curr = np.dot(invX, X.T)
curr

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [134]:
w = np.dot(curr, y)

In [135]:
w

array([  4.59494481, -63.56432501])